import { apiDelete, apiGet, apiPatch, apiPost } from "../lib/apiClient";
import { isSupabaseConfigured, supabase } from "../lib/supabase";
import type {
  Certificate,
  CertificateFormData,
  CertificateIssueSummary,
  PublicCertificate,
  SignatureData,
} from "../types/certificate";

const normalizeCertificate = (row: any): Certificate => ({
  ...row,
  certificate_title: row.certificate_title || row.title || "Certificate",
  template: row.template || row.template_style || "modern",
  issued_date: row.issued_date || row.issued_at || row.created_at,
  external_pdf_url: row.external_pdf_url || row.certificate_url || null,
  signature_data: Array.isArray(row.signature_data) ? row.signature_data : [],
  template_data: row.template_data && typeof row.template_data === "object" ? row.template_data : {},
  member_id: row.member_id || row.recipient_id,
});

const normalizePublicCertificate = (row: any): PublicCertificate => ({
  ...row,
  signature_data: Array.isArray(row.signature_data) ? row.signature_data : [],
  template_data: row.template_data && typeof row.template_data === "object" ? row.template_data : {},
});

export async function generateVerificationCode(): Promise<string> {
  throw new Error("Verification codes are generated by the Python backend when a certificate is issued.");
}

export async function checkDuplicateCertificate(memberId: string, eventId: string): Promise<boolean> {
  const certificates = await getCertificatesByEvent(eventId);
  return certificates.some((certificate) => certificate.member_id === memberId);
}

export async function issueSingleCertificate(formData: CertificateFormData): Promise<Certificate> {
  const row = await apiPost<Certificate>("/api/admin/certificates/issue", formData, { auth: true });
  return normalizeCertificate(row);
}

export async function issueCheckedInBulk(
  eventId: string,
  sharedFormData: Omit<CertificateFormData, "member_id" | "event_id">
): Promise<CertificateIssueSummary> {
  const summary = await apiPost<CertificateIssueSummary>(
    "/api/admin/certificates/issue-checked-in",
    { ...sharedFormData, event_id: eventId },
    { auth: true }
  );
  return {
    success: (summary.success || []).map(normalizeCertificate),
    skipped: summary.skipped || [],
    failed: summary.failed || [],
  };
}

export async function getCertificatesByEvent(eventId: string): Promise<Certificate[]> {
  const rows = await apiGet<Certificate[]>(`/api/admin/events/${eventId}/certificates`, { auth: true });
  return (rows || []).map(normalizeCertificate);
}

export async function getCertificatesByMember(_memberId: string): Promise<Certificate[]> {
  const rows = await apiGet<Certificate[]>("/api/me/certificates", { auth: true });
  return (rows || []).map(normalizeCertificate);
}

export async function getCertificateById(id: string): Promise<Certificate | null> {
  try {
    const row = await apiGet<Certificate>(`/api/certificates/${id}`, { auth: true });
    return normalizeCertificate(row);
  } catch (error: any) {
    if (error?.status === 404) return null;
    throw error;
  }
}

export async function getCertificateByVerificationCode(code: string): Promise<PublicCertificate | null> {
  const certificate = await getPublicCertificateByVerificationCode(code);
  if (!certificate || certificate.status === "revoked") return null;
  return certificate;
}

export async function getPublicCertificateByVerificationCode(code: string): Promise<PublicCertificate | null> {
  try {
    const row = await apiGet<PublicCertificate>(`/api/certificates/verify/${encodeURIComponent(code.toUpperCase())}`);
    return normalizePublicCertificate(row);
  } catch (error: any) {
    if (error?.status === 404) return null;
    throw error;
  }
}

export async function revokeCertificate(id: string): Promise<void> {
  await apiPost(`/api/admin/certificates/${id}/revoke`, {}, { auth: true });
}

export async function deleteCertificate(id: string): Promise<void> {
  await apiDelete(`/api/admin/certificates/${id}`, { auth: true });
}

export async function updateCertificate(
  id: string,
  updates: Partial<CertificateFormData>
): Promise<Certificate> {
  const row = await apiPatch<Certificate>(`/api/admin/certificates/${id}`, updates, { auth: true });
  return normalizeCertificate(row);
}

export async function uploadSignatureImage(file: File): Promise<string> {
  if (!isSupabaseConfigured || !supabase) {
    throw new Error("Supabase storage is not configured.");
  }

  const extension = file.name.split(".").pop() || "png";
  const path = `${crypto.randomUUID()}.${extension}`;

  const { error } = await supabase.storage.from("signatures").upload(path, file, {
    cacheControl: "3600",
    upsert: false,
  });

  if (error) throw new Error(`Could not upload signature image: ${error.message}`);

  const { data } = supabase.storage.from("signatures").getPublicUrl(path);
  return data.publicUrl;
}

export async function uploadCertificateTemplateImage(file: File): Promise<string> {
  if (!isSupabaseConfigured || !supabase) {
    throw new Error("Supabase storage is not configured.");
  }

  const extension = file.name.split(".").pop() || "png";
  const path = `${crypto.randomUUID()}.${extension}`;

  const { error } = await supabase.storage.from("certificate-templates").upload(path, file, {
    cacheControl: "3600",
    upsert: false,
  });

  if (error) throw new Error(`Could not upload certificate template: ${error.message}`);

  const { data } = supabase.storage.from("certificate-templates").getPublicUrl(path);
  return data.publicUrl;
}

export type { Certificate, CertificateFormData, PublicCertificate, SignatureData };
